FROM alpine
MAINTAINER Isabella Basso (isabbasso@riseup.net)
# volume mounting won't work with podman in the M1
# refer to https://dalethestirling.github.io/Macos-volumes-with-Podman/
VOLUME /images
COPY ./script-files/* .
COPY ./iso-files/ArchLinuxARM-aarch64-latest.tar.gz .
RUN chmod +x setup_arch.sh
RUN apk update && apk upgrade
RUN apk add multipath-tools dosfstools bash libarchive-tools gptfdisk e2fsprogs rsync
CMD ["./setup_arch.sh", "10G", "new_arch"]
