[user]
    name = "Isabella Basso"
    email = "isabellabdoamaral@usp.br"
[ui]
    color = "auto"
    editor = "nvim"
    diff-editor = "nvimdiff"
    merge-editor = "nvim -f -c \"Gvdiffsplit!\""
[aliases]
    b = ["branch"]
    r = ["rebase"]
# [git]
#     auto-local-branch = false
