[user]
name = "Isabella Basso"
email = "isabellabdoamaral@usp.br"

[snapshot]
max-new-file-size = "2M"

[ui]
default-command = "show"
color = "auto"
editor = "nvim"
diff-editor = "nvimdiff"
merge-editor = "nvim -f -c \"Gvdiffsplit!\""

# [git]
#     auto-local-branch = false

[aliases]
b = ["branch"]
bsa = ["branch", "set", "-r", "@-"]
bsam = ["branch", "set", "-r", "@-", "main"]
ca = ["checkout", "@-"]
cm = ["commit", "-m"]
d = ["describe"]
da = ["describe", "@-"]
e = ["edit"]
ep = ["edit", "@-"]
en = ["edit", "@+"]
gf = ["git", "fetch"]
gfu = ["git", "fetch", "--remote", "upstream"]
gp = ["git", "push"]
gpm = ["git", "push", "-b", "main"]
h = ["abandon"]
hide = ["abandon"]
la = ["log", "-r", "::@"]
mf = ["move", "-i", "--from"]
mt = ["move", "-i", "--to"]
r = ["rebase"]
rr = ["rebase", "-r"]
ra = ["rebase", "-s", "@"]
rs = ["rebase", "-s"]
s = ["split"]
sq = ["squash", "-i"]
